# generated by OpenBlock
import asyncio
import obespnow

async def _ob_task1():
  global msg
  while True:
    await asyncio.sleep(1)
    await asyncio.sleep_ms(0)

async def _ob_on_espnow():
  global msg
  msg = _ob_now.last_message
  _ob_now.broadcast(str((_ob_now.last_message)))

async def _ob_espnow_watch():
  while True:
    if _ob_now.poll():
      await _ob_on_espnow()
    await asyncio.sleep_ms(20)


msg = 0

_ob_now = obespnow.OBEspNow()


async def _ob_main():
  await asyncio.gather(_ob_task1(), _ob_espnow_watch())

asyncio.run(_ob_main())
