# generated by OpenBlock
from machine import Pin, SoftI2C
import bme280

temp = 0
humi = 0
pres = 0
alt = 0

_bme = bme280.BME280(SoftI2C(sda=Pin(21), scl=Pin(22)))

temp = _bme.temperature()
humi = _bme.humidity()
pres = _bme.pressure()
alt = _bme.altitude()
