# generated by OpenBlock
from machine import Pin
import asyncio
from machine import Pin, TouchPad

async def _ob_on_btn0_1():
  global hits
  hits += 1

async def _ob_btnwatch1():
  _last = p0.value()
  while True:
    _now = p0.value()
    if _now == 0 and _last != 0:
      await _ob_on_btn0_1()
    _last = _now
    await asyncio.sleep_ms(20)

async def _ob_on_touch4_2():
  global hits
  await asyncio.sleep(1)

async def _ob_touchwatch2():
  _touched = False
  while True:
    _v = _t4.read()
    if _v < 300 and not _touched:
      _touched = True
      await _ob_on_touch4_2()
    elif _v >= 300:
      _touched = False
    await asyncio.sleep_ms(20)

async def _ob_everybody3():
  global hits
  hits += 1

async def _ob_every3():
  while True:
    await asyncio.sleep(2)
    await _ob_everybody3()


hits = 0

p0 = Pin(0)
p0.init(Pin.IN, Pin.PULL_UP)
_t4 = TouchPad(Pin(4))


async def _ob_main():
  await asyncio.gather(_ob_btnwatch1(), _ob_touchwatch2(), _ob_every3())

asyncio.run(_ob_main())
