# generated by OpenBlock
import asyncio
import obwebremote

async def _ob_task1():
  global taps
  _ob_web.start_ap(str('OpenBlock'), str('12345678'))
  _ob_web.start()
  while True:
    _ob_web.set_label('L1', str((_ob_web.slider('S1'))))
    await asyncio.sleep(1)
    await asyncio.sleep_ms(0)

async def _ob_on_webbtnA_2():
  global taps
  taps += 1

async def _ob_webbtnwatch2():
  while True:
    if _ob_web.pressed('A'):
      await _ob_on_webbtnA_2()
    await asyncio.sleep_ms(20)


def repeat():
  _ob_web.poll()

taps = 0

_ob_web = obwebremote.OBWebRemote()
_ob_web.add_slider('S1')
_ob_web.add_button('A')


async def _ob_repeat_task():
  while True:
    repeat()
    await asyncio.sleep_ms(10)

async def _ob_main():
  await asyncio.gather(_ob_task1(), _ob_webbtnwatch2(), _ob_repeat_task())

asyncio.run(_ob_main())
