# generated by OpenBlock
from machine import Pin
import time
import machine

def _ob_sr04(trig, echo):
    tp = Pin(trig, Pin.OUT)
    ep = Pin(echo, Pin.IN, Pin.PULL_DOWN)
    tp.value(0)
    time.sleep_us(2)
    tp.value(1)
    time.sleep_us(10)
    tp.value(0)
    d = machine.time_pulse_us(ep, 1, 30000)
    if d == -2:
        return -1
    if d < 0:
        return 400
    return min(400, round(d / 58.0, 1))

dist = 0

while True:
  dist = _ob_sr04(5, 18)
