# generated by OpenBlock
import asyncio
from machine import Pin, SoftI2C
import ssd1306
from machine import Pin

def _oled_addr(i2c):
    try:
        devices = i2c.scan()
    except Exception:
        devices = []
    for address in (0x3C, 0x3D):
        if address in devices:
            return address
    return 0x3C

async def _ob_task1():
  global _oled_i2c, _oled
  _oled_i2c = SoftI2C(sda=Pin(21), scl=Pin(22), freq=400000)
  _oled = ssd1306.SSD1306_I2C(128, 64, _oled_i2c, addr=_oled_addr(_oled_i2c))
  _oled.text(str('hello'), int(0), int(0))
  _oled.show()

async def _ob_on_pin4_2():
  _oled.fill(0)
  _oled.text(str('pressed'), int(0), int(0))
  _oled.show()

async def _ob_watch2():
  _ob_last = p4.value()
  while True:
    _ob_now = p4.value()
    if _ob_now == 1 and _ob_last != 1:
      await _ob_on_pin4_2()
    _ob_last = _ob_now
    await asyncio.sleep_ms(20)


p4 = Pin(4)
p4.init(Pin.IN, Pin.PULL_DOWN)


async def _ob_main():
  await asyncio.gather(_ob_task1(), _ob_watch2())

asyncio.run(_ob_main())
