# generated by OpenBlock
import asyncio
from machine import Pin, PWM
import time

_buzzers = {}
def _ob_buzzer(pin):
    if pin not in _buzzers:
        _buzzers[pin] = PWM(Pin(pin))
        _buzzers[pin].duty_u16(0)
    return _buzzers[pin]
def _ob_buzzer_tone(pin, freq, dur):
    _b = _ob_buzzer(pin)
    _b.freq(int(freq))
    _b.duty_u16(32768)
    time.sleep(dur)
    _b.duty_u16(0)

async def _ob_buzzer_tone_async(pin, freq, dur):
    _b = _ob_buzzer(pin)
    _b.freq(int(freq))
    _b.duty_u16(32768)
    await asyncio.sleep(dur)
    _b.duty_u16(0)

async def _ob_task1():
  while True:
    await _ob_buzzer_tone_async(4, 262, 1)
    await asyncio.sleep(0.5)
    await asyncio.sleep_ms(0)

async def _ob_task2():
  while True:
    await asyncio.sleep(0.2)
    await asyncio.sleep_ms(0)



async def _ob_main():
  await asyncio.gather(_ob_task1(), _ob_task2())

asyncio.run(_ob_main())
