# generated by OpenBlock
import random

scores = []
report = 0

del scores[0:]
for count in range(5):
  scores.append(random.randint(1, 100))
report = (str('first=') + str(scores[1 - 1]))
if '50' in scores:
  del scores[1 - 1]
