# generated by OpenBlock
import asyncio

async def _ob_task1():
  global score
  score = 0
  while True:
    score += 1
    await asyncio.sleep(1)
    await asyncio.sleep_ms(0)

async def _ob_task2():
  global score
  while not score > 5:
    await asyncio.sleep_ms(10)
  score = 'done'


score = 0


async def _ob_main():
  await asyncio.gather(_ob_task1(), _ob_task2())

asyncio.run(_ob_main())
