# generated by OpenBlock
import asyncio
from machine import Pin

async def _ob_task1():
  global score
  while True:
    score += 1
    await asyncio.sleep(1)
    await asyncio.sleep_ms(0)

async def _ob_on_pin4_2():
  global score
  score = 0

async def _ob_watch2():
  _ob_last = p4.value()
  while True:
    _ob_now = p4.value()
    if _ob_now == 1 and _ob_last != 1:
      await _ob_on_pin4_2()
    _ob_last = _ob_now
    await asyncio.sleep_ms(20)


score = 0

p4 = Pin(4)
p4.init(Pin.IN, Pin.PULL_DOWN)


async def _ob_main():
  await asyncio.gather(_ob_task1(), _ob_watch2())

asyncio.run(_ob_main())
